Num GPUs Available:  0
Num CPUs Available:  1
Num TPUs Available:  0
Loaded 360 sequences
Traceback (most recent call last):
  File "e:\Dev\Deakin\Project_Orion\DataScience\Models\Action Recognition\Train.py", line 109, in <module>
    TC.train_model()
  File "e:\Dev\Deakin\Project_Orion\DataScience\Models\Action Recognition\Train.py", line 94, in train_model
    self.model.add(LSTM(100, return_sequences=False,return_state=True))
  File "C:\Python310\lib\site-packages\tensorflow\python\trackable\base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python310\lib\site-packages\keras\engine\sequential.py", line 236, in add
    raise ValueError(SINGLE_LAYER_OUTPUT_ERROR_MSG)
ValueError: All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.